# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d058ea9a9e27de84c6ebd12fad9fe9f99df2f05431ab41f304c3c4b0e4f17e2a4fc1ae930a0b5dd1cb27087a5b90e757cb2cb2b5c3e4dfb535472fe4ab259312

test:
  secret_key_base: d82893d51ca478d32be66da0efae614def4622b4ffbb83f1a9c8d64ad0d4b9b61620ec54e489ecbc04ae25337d2054c99ac4e8db2b7334d8e54c9dcabda481cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
